### ISSUE TITLE
 Error in yaml.load

### ISSUE THREAD

**Issue by jimijimiyo** [achetverikov/visual_search_db#11]
Encounter an error whily try to parse datasets, which parsed correctly in the earlier version:

Error in yaml.load(paste(readLines(input, encoding = "UTF-8"), collapse = "\n"), : 
Scanner error: mapping values are not allowed in this context at line 50, column 165

**Comment by jimijimiyo** [comment]
I think it may be due to absence of required fields (like License), but these are is not at line 50. Nevertheless, I'll check again after fixing it

**Comment by achetverikov** [comment]
fixed, was due to a colon used in a field description (colons are special symbols in YAML)
now we only need to transform old configs to a new format
